export default {
  PRODUCTS_DELETE: 'PRODUCTS_DELETE',
  PRODUCTS_FETCH: 'PRODUCTS_FETCH',
  PRODUCTS_SAVE: 'PRODUCTS_SAVE',
  PRODUCTS_SET: 'PRODUCTS_SET',
  SAVE_TO_CART: 'SAVE_TO_CART',
  DELETE_FROM_CART: 'DELETE_FROM_CART'
}
